config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "home_pages#top"
  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :boards, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit destroy], shallow: true
  end

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_many :comments, dependent: :destroy

  # mount_uploader :board_image, BoardImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy

  def own?(object)
    id == object&.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  before_action :require_login
  add_flash_types :success, :danger

  private

  def not_authenticated
    redirect_to login_path, danger: t("defaults.flash_message.require_login")
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, success: "投稿に成功しました"
    else
      flash.now[:danger] = t("defaults.flash_message.not_created", item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), success: "更新に成功しました"
    else
      flash.now[:danger] = "更新に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy!
    redirect_to boards_path, success: t("defaults.flash_message.deleted", item: Board.model_name.human), status: :see_other
  end

  private

  def board_params
    params.require(:board).permit(:title, :body, :board_image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to board_path(@comment.board), success: t("defaults.flash_message.created", item: Comment.model_name.human)
    else
      redirect_to board_path(@comment.board), danger: t("defaults.flash_message.not_created", item: Comment.model_name.human)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(board_id: params[:board_id])
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
    skip_before_action :require_login, only: %i[top]
    def top; end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to boards_path, success: "ログインしました"
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, danger: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: "ユーザー登録が完了しました"
    else
      render :new, danger: "ユーザー登録に失敗しました"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_background_color(type)
    case type.to_sym
    when :success then "bg-green-500"
    when :danger then "bg-red-500"
    when :error then "bg-yellow-500"
    else "bg-gray-500"
    end
  end
end

app/views/boards/_board.html.erb
<div id="board-id-<%= board.id %>" class="max-w-sm w-full bg-white border border-gray-400 rounded-lg shadow-md overflow-hidden">
  <div class="h-48 bg-cover bg-center rounded-t-lg">
  <%= image_tag(board.board_image.present? ? image_path(board.board_image) : asset_path('beer1.png'), class: "object-cover h-full w-full") %>
  </div>
  <div class="p-4">
    <div class="mb-4">
      <div class="text-gray-900 font-bold text-xl mb-2"><%= link_to board.title, board_path(board) %></div>
      <% if current_user == board.user %>
      <div class="flex justify-end space-x-2">
        <%= link_to edit_board_path(board), id: "button-edit-#{board.id}" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 2.487a2.25 2.25 0 013.182 3.182l-12 12-4.5 1.5 1.5-4.5 12-12z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 5.25L18.75 6" />
          </svg>
        <% end %>
        <%= link_to board_path(board), id: "button-delete-#{board.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, class: "ml-2" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 6.75l-.857 12.008A2.25 2.25 0 0116.402 21H7.598a2.25 2.25 0 01-2.241-2.242L4.5 6.75M9.75 9.75v7.5m4.5-7.5v7.5M3 6.75h18M12 3.75h.008v.008H12V3.75z" />
          </svg>
        <% end %>
      </div>
      <% end %>
      <p class="text-gray-700 text-base"><%= board.body %></p>
    </div>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with model: @board, class: "space-y-4" do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  <div class="mb-4">
    <%= f.label :title, class: "block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4" %>
    <%= f.text_field :title, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
  </div>

  <div class="mb-4">
    <%= f.label :body, class: "block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4" %>
    <%= f.text_area :body, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", rows: "10" %>
  </div>

  <div class="image-selection">
    <%= f.label :board_image, "ビールを選択してください", class: "block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4"  %>
    <div class="grid grid-cols-3 gap-4 justify-center">
      <% ["beer1.png", "beer2.png", "beer3.png"].each do |image| %>
        <div class="flex flex-col items-center">
          <%= f.radio_button :board_image, image, class: "mb-2" %>
          <%= image_tag image_path(image), size: "100x100", class: "rounded" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="flex justify-center">
    <%= f.submit 'Submit', class: "text-yellow-400 hover:text-white border border-yellow-400 transition hover:bg-yellow-500 duration-300 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-3xl px-5 py-2.5 text-center me-2 mb-2 dark:border-yellow-300 dark:text-yellow-300 dark:hover:text-white dark:hover:bg-yellow-400 dark:focus:ring-yellow-900" %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="max-w-2xl mx-auto p-4">
  <h1 class="text-3xl font-bold mb-6 block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4"><%= t('.title') %></h1>
  <%= render 'form', board: @board %>
</div>

app/views/boards/index.html.erb
<%= render 'layouts/flash_messages' %>
<div>
 <form>
  <div class="flex mb-3">
    <input class="form-input flex-grow p-2 border border-gray-300 rounded-l" placeholder="検索ワード" type="search" />
    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-r">検索</button>
  </div>
  </form>
</div>
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 justify-items-center">
<% if @boards.present? %>
  <%= render @boards %>
<% else %>
  <div>掲示板がありません</div>
<% end %>
</div>
<div class="grid justify-items-center">
<% if @boards.present? %>
  <div class="mt-4">
    <%= paginate @boards %>
  </div>
<% end %>
</div>

app/views/boards/new.html.erb
<div class="max-w-2xl mx-auto p-4">
  <h1 class="text-3xl font-bold mb-6 block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4"><%= t('.title') %></h1>
  <%= form_with model: @board, class: "space-y-4" do |f| %>
    <div class="mb-4">
      <%= f.label :title, class: "block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4" %>
      <%= f.text_field :title, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <div class="mb-4">
      <%= f.label :body, class: "block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4" %>
      <%= f.text_area :body, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", rows: "10" %>
    </div>
    <div class="mb-4">
      <%= f.label :board_image, class: "block text-gray-700 text-sm font-medium mb-1" %>
      <%= f.file_field :board_image, class: "block w-full p-2 border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" , accept: 'image/*' %>
      <%= f.hidden_field :board_image_cache %>
    </div>
    <div class="flex justify-center" >
      <%= f.submit 'Submit', class: "text-yellow-400 hover:text-white border border-yellow-400 transition hover:bg-yellow-500 duration-300 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-3xl px-5 py-2.5 text-center me-2 mb-2 dark:border-yellow-300 dark:text-yellow-300 dark:hover:text-white dark:hover:bg-yellow-400 dark:focus:ring-yellow-900" %>
    </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<%= render 'layouts/flash_messages' %>
<div class="container mx-auto pt-5">
  <div class="mb-3">
    <div class="lg:w-2/3 lg:mx-auto">
      <h1 class="text-2xl mt-4 lg:mt-0 text-yellow-200 hover:text-white mr-4"><%= t('.title') %></h1>
      <article class="bg-white shadow-md rounded-lg overflow-hidden">
        <div class="p-5">
          <div class="flex">
            <%= image_tag(@board.board_image.present? ? image_path(@board.board_image) : asset_path('beer1.png'), class: "object-cover w-24 h-24 lg:w-75 lg:h-50") %>
            <div class="ml-4 w-full">
              <h3 class="text-xl font-semibold"><%= @board.title %></h3>
              <div class="flex justify-end mt-2">
                <%= link_to edit_board_path(@board), id: "button-edit-#{@board.id}" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 2.487a2.25 2.25 0 013.182 3.182l-12 12-4.5 1.5 1.5-4.5 12-12z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 5.25L18.75 6" />
                  </svg>
                <% end %>
                <%= link_to board_path(@board), id: "button-delete-#{@board.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, class: "ml-2" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 6.75l-.857 12.008A2.25 2.25 0 0116.402 21H7.598a2.25 2.25 0 01-2.241-2.242L4.5 6.75M9.75 9.75v7.5m4.5-7.5v7.5M3 6.75h18M12 3.75h.008v.008H12V3.75z" />
                  </svg>
                <% end %>
              </div>
              <p class="mt-4"><%= simple_format(@board.body) %></p>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
  <%= render 'comments/form', comment: @comment, board: @board %>
  <div class="mb-5">
    <div class="lg:w-2/3 lg:mx-auto">
      <table class="min-w-full bg-white rounded-lg overflow-hidden">
        <tbody id="table-comment">
          <%= render @comments %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>" class="border-b">
  <!-- 画像表示部分 -->
  <!-- コメント本文とユーザー名 -->
  <td class="pl-4">
    <p class="text-gray-700 mt-1"><%= simple_format(comment.body) %></p>
  </td>

  <!-- アクションボタン -->
  <% if current_user.own?(comment) %>
    <td class="text-right">
      <ul class="inline-flex space-x-2">
        <!-- 編集ボタン -->
        <li>
          <%= link_to "#", class: "edit-comment-link" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-gray-500 hover:text-gray-700" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M12 20h9" />
              <path d="M16.5 3.5a2.121 2.121 0 1 1 3 3L7 19.5 3 21l1.5-4L16.5 3.5z" />
            </svg>
          <% end %>
        </li>
        <!-- 削除ボタン -->
        <li>
          <%= link_to "#", class: "delete-comment-link" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-red-500 hover:text-red-700" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M3 6h18" />
              <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
              <path d="M10 11v6" />
              <path d="M14 11v6" />
              <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" />
            </svg>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<div class="mb-3" id="comment-form">
  <div class="lg:w-2/3 lg:mx-auto">
    <%= form_with model: comment, url: board_comments_path(board), class: "space-y-4" do |f| %>
      <div>
        <%= f.label :body, class: "block text-sm font-medium text-gray-700" %>
        <%= f.text_area :body, class: "form-textarea mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", rows: "4", placeholder: Comment.human_attribute_name(:body) %>
      </div>
      <div class="flex justify-center">
        <%= f.submit 'コメント投稿', class: "text-yellow-400 hover:text-white border border-yellow-400 transition hover:bg-yellow-500 duration-300 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-2xl px-5 py-2.5 text-center me-2 mb-2 dark:border-yellow-200 dark:text-yellow-200 dark:hover:text-white dark:hover:bg-yellow-400 dark:focus:ring-yellow-900" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
 <div class="<%= flash_background_color(message_type) %> px-4 py2 rounded-md text-white mb-4">
   <%= message %>
 </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bairs" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <!--
    <link rel="manifest" href="/manifest.json">
    -->
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/4.1.3/css/flag-icons.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body style="background: linear-gradient(to bottom, #000000, #3558a3);">
  <% if logged_in? %>
    <%= render 'shared/header' %>
  <% else %>
    <%= render 'shared/before_login_header' %>
  <% end %>
    <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/profiles/edit.html.erb
<br>
<div class="m-auto overflow-hidden rounded-lg shadow-lg cursor-pointer h-300 max-w-5xs sm:max-w-5sm md:max-w-5md lg:max-w-5lg xl:max-w-5xl bg-white">
<div class="container mx-auto">
  <div class="flex justify-center">
    <div class="w-full md:w-5/6 lg:w-2/3">
      <h1 class="text-2xl font-bold mb-6"><%= t('.title') %></h1>
      <%= form_with model: @user, url: profile_path, method: :put, class: "space-y-6" do |f| %>
        <div>
          <%= f.label :email, class: "block text-sm font-medium text-gray-700" %>
          <%= f.email_field :email, class: "mt-1 block w-full border-2 border-black rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>
        <div>
          <%= f.label :last_name, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :last_name, class: "mt-1 block w-full border-2 border-black rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>
        <div>
          <%= f.label :first_name, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :first_name, class: "mt-1 block w-full border-2 border-black rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>
        <div>
          <%= f.label :avatar, class: "block text-sm font-medium text-gray-700" %>
          <%= f.file_field :avatar, class: "mt-1 block w-full text-sm text-gray-900 border-black rounded-md cursor-pointer focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
          <%= f.hidden_field :avatar_cache %>
          <div class="mt-3">
            <%= image_tag "sample", class: "rounded-full w-24 h-24", id: 'preview' %>
          </div>
        </div>
        <%= f.submit class: "w-full bg-indigo-600 text-white font-bold py-2 px-4 rounded hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
      <% end %>
      <div class="text-center mt-6">
        <%= link_to t('.to_login_page'), login_path, class: "text-indigo-600 hover:underline" %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/profiles/show.html.erb
<br>
<div class="m-auto overflow-hidden rounded-lg shadow-lg cursor-pointer h-300 max-w-5xs sm:max-w-5sm md:max-w-5md lg:max-w-5lg xl:max-w-5xl bg-white">
<div class="container mx-auto pt-3">
  <div class="flex justify-center">
    <div class="w-full md:w-10/12">
      <div class="flex justify-between items-center mb-5">
        <h1 class="text-xl font-bold"><%= t('.title') %></h1>
        <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded' %>
      </div>
      <table class="table-auto w-full">
        <tr>
          <th class="text-left font-semibold p-2"><%= User.human_attribute_name(:email) %></th>
          <td class="p-2"><%= current_user.email %></td>
        </tr>
        <tr>
          <th class="text-left font-semibold p-2"><%= User.human_attribute_name(:first_name) %></th>
          <td class="p-2"><%= current_user.first_name %></td>
        </tr>
        <tr>
          <th class="text-left font-semibold p-2"><%= User.human_attribute_name(:avatar) %></th>
          <td class="p-2"><%= image_tag 'sample', class: 'rounded-full w-12 h-12' %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="flex flex-col lg:flex-row items-center justify-between bg-black p-6">
  <div class="flex justify-center w-full lg:w-auto mb-4 lg:mb-0">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', alt: 'Logo' %>
      <% end %>
  </div>
  <div class="text-sm lg:flex-grow flex justify-center lg:justify-end">
    <%= link_to 'ビール投稿', boards_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4' %>
    <%= link_to t('header.login'), login_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4' %>
    <%= link_to '新規登録', new_user_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white' %>
  </div>
  </nav>
</header>


<!-- Dropdown menu -->

app/views/shared/_header.html.erb
<header>
  <nav class="flex flex-col lg:flex-row items-center justify-between bg-black p-6">
  <div class="flex justify-center w-full lg:w-auto mb-4 lg:mb-0">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', alt: 'Logo' %>
    <% end %>
  </div>
  <div class="text-sm lg:flex-grow flex justify-center lg:justify-end">
      <%= link_to profile_path, class: 'flex items-center' do %>
        <%= image_tag 'sample.jpg', class: 'rounded-full mr-4', width: '40', height: '80' %>
      <% end %>
      <%= link_to 'ビール投稿一覧', boards_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4' %>
      <%= link_to t('header.create_board'), new_board_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4' %>
      <%= link_to t('header.logout'), logout_path,method: :delete, data: { turbo_method: :delete }, class: 'block mt-4 lg:inline-block lg:mt-0 text-yellow-200 hover:text-white mr-4' %>
  </div>
</nav>
</header>

app/views/user_sessions/new.html.erb
<br>
<div class="max-w-sm m-auto overflow-hidden rounded-lg shadow-lg cursor-pointer h-300 max-w-5xs sm:max-w-5sm md:max-w-5md lg:max-w-5lg xl:max-w-5xl">
  <div class="block w-auto h-full bg-white">
    <h1><%= t('.title') %></h1>
    <div class=" flex items-center justify-center" >
      <%= form_with url: login_path do |f| %>
        <div class="mb-3">
          <%= f.label :email, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.email_field :email, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.password_field :password, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <%= f.submit "ログイン", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      <% end %>
    </div>
    <div class='text-center'>
      <%= link_to t('.to_register_page'), new_user_path %>
      <%= link_to t('.password_forget'), '#' %>
    </div>
  </div>
</div>